### ISSUE TITLE
Can't import bold fonts on Mac (10.7.5)

### ISSUE THREAD

**Issue by martinhanzalek** [vjpr/monaco-bold#1]
Hi, thanks for great work with the bold variant of Monaco font. However, I can't make my Mac import it (the *-Bold.otf files). If I drop the files on Font-Book, it raises warning:

![image](https://f.cloud.github.com/assets/795986/686941/a4135302-da6b-11e2-8d22-71fe5dd9c00b.png)

which says, that some of the font properties are wrong. If I try to import the font it doesn't appear in the list of my fonts.

How to solve this?

**Comment by vjpr** [comment]
Don't worry about the problems. I received the same when I imported and it worked fine.

The issue is with the `Duplicate fonts` warning. This will prevent the font from showing up, or you may already have it installed.

I can't remember if I got a `System Validation` error, but its probably not a big deal.

---

In Font Book goto the `User` collection and have a look for the MonacoB fonts.

If you click the info icon you will see all the properties of the fonts.

Have a look at the `Unique name` property of the fonts. What does it say?

**Comment by martinhanzalek** [comment]
Hi, sorry for my late answer… It didn't work on Mac OS 10.7, however I
upgraded to 10.8 now and the import is working (is still says some minor
errors, but it doesn't prevent me from installing the font). It's weird,
I'd suppose the version of OS doesn't matter in this, but it probably does.

Anyway – thanks for your work, I like the font more than Menlo provided by
system.

Pěkný den, zdravím, Martin Hanzálek.

## 

Mgr. Martin Hanzálek
e-mail: martin.hanzalek@gmail.com
mobile: +420 773 648 726

**Comment by vjpr** [comment]
Glad you like it!

**Comment by pavel-dolgov** [comment]
Have the same problem with validation on 10.7.5. Is there any solution beside upgrading OS?

**Comment by vjpr** [comment]
Follow the instructions in my previous post - ill need more info to debug
as I'm not running 10.7.x

**Comment by pavel-dolgov** [comment]
Thank you for the response. I tried your instruction, it didn't help, unfortunately. So I converted font to ttf (http://www.freefontconverter.com/) and then I was able install ttf successfully. Now there is another problem, looks like bold ignored by IDEA, I can see only regular characters, like with the original Monaco. I'm using version 12.1.4 what version of IDEA do you use?

**Comment by vjpr** [comment]
I use version 12 too. Make sure you are using the `MonacoB` font instead of
`Monaco`. Go into your colors and fonts preferences and check that the
style is actually bold. Check in the OSX font book that the font is
actually bold too.

Could you send me a screenshot of the font book info for MonacoB and
MonacoB-Bold, that might help me debug.

Also note that the MonacoB is quite subtle at pt 10 font so you might not
have noticed it.

**Comment by pavel-dolgov** [comment]
Don't know what happened, but works fine now. Like the font, thank you very much for your work.

**Comment by sureshs592** [comment]
I face the same issue too (running OS X 10.7.5). Thanks @pavel-dolgov for your ttf workaround. Worked for me! Great stuff @vjpr ! This project was exactly what I was looking for. :D
